dist: trusty
language: generic
before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
install:
    - sudo apt-get install -qq g++-6
    - alias gcc=gcc-6
    - alias g++=g++-6
    - sudo apt-get install -qq scons
script:
    - time scons
    - scons -c