dist: trusty
language: generic
before_install:
    - sudo apt-get update -qq
install:
    - sudo apt-get install -qq g++-4.8
    - alias gcc=gcc-4.8
    - alias g++=g++-4.8
    - sudo apt-get install -qq scons
script:
    - time scons
    - scons -c