language: cpp
sudo: required
dist: trusty
compiler:
- gcc
os:
- linux

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update
- sudo apt-get install g++-6
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
- sudo apt-get install libboost-dev

script:
- time scons
